### ISSUE TITLE
Log File Contents

### ISSUE THREAD

**Issue by bigmacd** [ElectronicCats/flipper-addons#5]
I have not been able to find any information about what is in the log files.  This is the possibly the most important feature for me.  Do you have examples?

Thanks.

**Comment by xpeqex** [comment]
Hi @bigmacd 

Could you please indicate to me what add-on/shield are you using? 
Additionally, share detailed information about the log files you are mentioning. Please note that this repository is for the hardware, but we are happy to work with you if it is an application developed by us.

**Comment by bigmacd** [comment]
Ah, sorry about that.  This is for the Flipper Can Bus add-on.  One of its functions include "Read LOG" and I'm curious what is captured in those logs.  My hope it is Can Bus messages!

**Comment by xpeqex** [comment]
I will close this issue now. If you have any query related to the hardware feel free to open a new issue in this repo, otherwise please check the other repositories for the apps.
